export const exerciseList = [
    "Arnold Press",
    "Back Squat",
    "Barbell Deadlift",
    "Barbell Hip Thrust",
    "Barbell Overhead Press",
    "Barbell Row",
    "Bench Press",
    "Bicep Concentration Curl",
    "Bicep Hammer Curl",
    "Bicep Preacher Curl",
    "Bulgarian Split Squat",
    "Cable Crossover",
    "Cable Crunch",
    "Cable Lateral Raise",
    "Calf Raise (Standing)",
    "Calf Raise (Seated)",
    "Chest Fly",
    "Close‑Grip Bench Press",
    "Clean and Press",
    "Decline Bench Press",
    "Decline Dumbbell Fly",
    "Deadlift (Sumo)",
    "Deadlift (Traditional)",
    "Dips",
    "Dumbbell Bench Press",
    "Dumbbell Curl (Standing)",
    "Dumbbell Fly",
    "Dumbbell Lateral Raise",
    "Dumbbell Lunges",
    "Dumbbell Overhead Press",
    "Dumbbell Pullover",
    "Dumbbell Row (Single‑Arm)",
    "Face Pull",
    "Flutter Kicks",
    "Front Squat",
    "Glute Bridge",
    "Good Morning",
    "Hack Squat",
    "Hamstring Curl (Prone)",
    "Hamstring Curl (Seated)",
    "Hanging Leg Raise",
    "Hanging Knee Raise",
    "Hip Thrust",
    "Incline Bench Press",
    "Incline Dumbbell Bench Press",
    "Incline Dumbbell Fly",
    "Incline Dumbbell Press",
    "Inverted Row",
    "Jump Rope",
    "Kettlebell Swing",
    "Landmine Press",
    "Lat Pulldown",
    "Leg Extension",
    "Leg Press",
    "Leg Raise (Hanging)",
    "Lunge (Walking)",
    "Lunge (Static)",
    "Mountain Climbers",
    "Overhead Press (Military Press)",
    "Pendlay Row",
    "Plank",
    "Pole‑Assisted Pull‑Up",
    "Pull‑Up",
    "Push‑Up",
    "Push‑Up (Close‑Grip)",
    "Push‑Up (Wide)",
    "Pull‑Up (Chin‑Up)",
    "Renegade Row",
    "Romanian Deadlift",
    "Row (Seated Cable Row)",
    "Russian Twist",
    "Shrug (Barbell)",
    "Sit‑Up",
    "Smith Machine Bench Press",
    "Smith Machine Bench Press (Incline)",
    "Smith Machine Squat",
    "Smith Machine Shoulder Press",
    "Split Squat (Front)",
    "Split Squat (Bulgarian)",
    "T‑Bar Row",
    "Tricep Bar Pushdown",
    "Tricep Cable Pushdown",
    "Tricep Extension (Overhead)",
    "Walking Lunge",
    "Wrist Curl (Dumbbell)",
    "Z‑Press",
];